openapi: 3.0.0
info:
  description: Person Read API
  version: "1.0.0"
  title: Person Read API
  contact:
    email: davetii@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: http://localhost:8081/api
    description: Local Server
    
paths:
  /v1/person/{personId}:
    get:
      summary: returns a given person
      description: returns a given person
      operationId: fetchPerson
      parameters:
        - $ref: "#/components/parameters/personIdPathParam"
      responses:
        '200':
          description: returns a given person
          content:
            application/json:
              schema:
                $ref: "person.yml#/components/schemas/Person"
        '404':
          description: Not Found
components:
  parameters:

    personIdPathParam:
      in: path
      description: personid
      name: personId
      required: true
      schema:
        type: string