openapi: 3.0.0
info:
  description: Reports API
  version: "1.0.0"
  title: Reports API
  contact:
    email: davetii@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: http://localhost:8084/api
    description: Local Server

paths:
  /v1/reports/person/id/{id}:
    get:
      summary: returns a person by looking up the ID
      description: returns a person
      operationId: fetchById
      parameters:
        - $ref: "#/components/parameters/idPathParam"
      responses:
        '200':
          description: returns list of people with specific role
          content:
            application/json:
              schema:
                $ref: "person.yml#/components/schemas/Person"
        '404':
          description: Not Found
  /v1/reports/person/role/{role}:
    get:
      summary: returns a list of people with a specific role
      description: returns a list of people with a specific role
      operationId: fetchByRole
      parameters:
        - $ref: "#/components/parameters/rolePathParam"
      responses:
        '200':
          description: returns list of people with specific role
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "person.yml#/components/schemas/Person"
        '404':
          description: Not Found
  /v1/reports/person/level/{level}:
    get:
      summary: returns a list of people with a specific level
      description: returns a list of people with a specific level
      operationId: fetchByLevel
      parameters:
        - $ref: "#/components/parameters/levelPathParam"
      responses:
        '200':
          description: returns list of people with specific level
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "person.yml#/components/schemas/Person"
        '404':
          description: Not Found
  /v1/reports/person/org/{orgid}:
    get:
      summary: returns a list of people within a specific org
      description: returns a list of people within a specific org
      operationId: fetchOrgMembers
      parameters:
        - $ref: "#/components/parameters/orgPathParam"
      responses:
        '200':
          description: returns list of people with specific level
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "person.yml#/components/schemas/Person"
        '404':
          description: Not Found

  /v1/reports/org/{orgid}:
    get:
      summary: returns a specific org, its leader and its members
      description: returns a list of people within a specific org
      operationId: fetchOrg
      parameters:
        - $ref: "#/components/parameters/orgPathParam"
      responses:
        '200':
          description: returns list of people with specific level
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/org"
        '404':
          description: Not Found

  /v1/reports/person/locale/{locale}:
    get:
      summary: returns a list of people within a specific locale
      description: returns a list of people within a specific locale
      operationId: fetchByLocale
      parameters:
         - $ref: "#/components/parameters/localePathParam"
      responses:
        '200':
          description: returns list of people with specific locale
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "person.yml#/components/schemas/Person"
        '404':
          description: Not Found
  /v1/reports/person/email/{email}:
    get:
      summary: returns a Person associated with an email
      description: returns a Person associated with an email
      operationId: fetchByEmail
      parameters:
        - $ref: "#/components/parameters/emailPathParam"
      responses:
        '200':
          description: returns a Person associated with an email
          content:
            application/json:
              schema:
                $ref: "person.yml#/components/schemas/Person"
        '404':
          description: Not Found
components:
  parameters:

    idPathParam:
      in: path
      description: id
      name: id
      required: true
      schema:
        type: string

    rolePathParam:
      in: path
      description: role
      name: role
      required: true
      schema:
        type: string

    levelPathParam:
      in: path
      description: level
      name: level
      required: true
      schema:
        type: string

    orgPathParam:
      in: path
      description: orgid
      name: orgid
      required: true
      schema:
        type: string

    localePathParam:
      in: path
      description: locale
      name: locale
      required: true
      schema:
        type: string

    emailPathParam:
      in: path
      description: email
      name: email
      required: true
      schema:
        type: string


  schemas:
    org:
      type: object
      description: Org
      properties:
        name:
          type: string
          example: SERVICE
        leader:
          $ref: "person.yml#/components/schemas/Person"
        members:
          type: array
          items:
            $ref: "person.yml#/components/schemas/Person"