# Use postgres/example user/password credentials
version: '3.9'

services:

  postgres:
    image: postgres
    container_name: postgres-test
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=turner

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8083:8080"

  mongodb:
      image: mongodb/mongodb-community-server
      container_name: mongodb-test
      restart: always
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_DATABASE: "test"

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka-test
    restart: always
    ports:
      - "9092:9092"

