# Use postgres/example user/password credentials
version: '3.9'

services:

  mongodb:
      image: mongodb/mongodb-community-server
      container_name: mongodb-personwrite-verify
      restart: always
      ports:
        - "27018:27017"
      environment:
        MONGO_INITDB_DATABASE: "personwrite-verify"

  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka-personwrite-verify
    restart: always
    ports:
      - "9092:9092"

