openapi: 3.0.0
info:
  description: Person Write API
  version: "1.0.0"
  title: Person Write API
  contact:
    email: davetii@gmail.com
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'

servers:
  - url: http://localhost:8080/api
    description: Local Server

paths:
  /v1/person/:
    put:
      summary: Update Person
      description: Update Person
      operationId: updatePerson
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        '200':
          description: Person Updated
        '404':
          description: Not Found
    post:
      summary: Create Person
      description: Create
      operationId: createPerson
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Person"
      responses:
        '200':
          description: Person Created
components:
  schemas:
    Person:
      type: object
      description: Person
      properties:
        id:
          type: string
          example: abc123
        firstName:
          type: string
          example: Dave
        lastName:
          type: string
          example: Turner
        role:
          type: string
          enum: [DEV, TESTER, BA, MGR]
        email:
          type: string
          example: davetii@gmail.com
        addr1:
          type: string
          example: 123 nowhere
        addr2:
          type: string
          example: po box 34
        city:
          type: string
          example: harrison
        region:
          type: string
          example: MI
        country:
          type: string
          example: US
        phone1:
          type: string
          example: 15868736131
        phone2:
          type: string
          example: 15868736131
