services:

  mongodb:
      image: mongodb/mongodb-community-server
      container_name: mongodb-personread-verify
      restart: always
      ports:
        - "27018:27017"
      environment:
        MONGO_INITDB_DATABASE: "personread-verify"
      volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

